baseURL = 'https://blog.codejustin.dev'
languageCode = 'en-us'
title = 'CodeClicks && CulinaryBits'
theme = 'ficurinia'
defaultContentLanguage = 'en'


[params]

author = 'Justin Kuennen'
description = 'A Blog spot to share information and updates about the many hobbies (Coding, Photography, Cooking, Old Tech, etc) that interest me (Justin Kuennen).'
posts = 'posts'
showPostsLink = true
logo = '/Crunchy-Bundled.svg'
favicon = "/Crunchy-(Small).png"

contentWidth = "1200px"

monospaceFontFamily = "Space Mono"
fontFamily = "Space Mono"          # changes the font, default "JetBrains Mono"
[menu]
[[menu.icons]]
identifier = 'github'
name = 'Github'
url = 'https://github.com/ImJustinTIme'
weight = 20
